"""Incremental graph update logic.

Adapted from code-review-graph (MIT), modified to use the plugin parser registry.
"""

from __future__ import annotations

import fnmatch
import hashlib
import logging
import os
import subprocess
import time
from pathlib import Path
from typing import Optional

import json as _json

from .crossref import cross_reference_detector
from .graph import GraphStore
from .models import EdgeInfo, NodeInfo
from .parsers import get_parser, parse_file, supported_extensions

logger = logging.getLogger(__name__)

DEFAULT_IGNORE_PATTERNS = [
    ".code-rosetta/**",
    ".code-review-graph/**",
    "node_modules/**",
    ".git/**",
    "__pycache__/**",
    "*.pyc",
    ".venv/**",
    "venv/**",
    "dist/**",
    "build/**",
    ".next/**",
    "target/**",
    "*.min.js",
    "*.min.css",
    "*.map",
    "*.lock",
    "package-lock.json",
    "yarn.lock",
    "*.db",
    "*.sqlite",
    "*.db-journal",
    "*.db-wal",
    ".terraform/**",
    ".terraform.lock.hcl",
]


def find_repo_root(start: Path | None = None) -> Optional[Path]:
    current = start or Path.cwd()
    while current != current.parent:
        if (current / ".git").exists():
            return current
        current = current.parent
    if (current / ".git").exists():
        return current
    return None


def find_project_root(start: Path | None = None) -> Path:
    root = find_repo_root(start)
    return root if root else (start or Path.cwd())


def get_db_path(repo_root: Path) -> Path:
    from .config import cfg

    group_db = cfg.resolve_db_for_repo(repo_root)
    if group_db != cfg.default_db:
        # Repo belongs to a named group — use shared DB
        group_db.parent.mkdir(parents=True, exist_ok=True)
        return group_db

    # Fallback: repo-local DB
    crg_dir = repo_root / ".code-rosetta"
    new_db = crg_dir / "graph.db"
    crg_dir.mkdir(exist_ok=True)

    inner_gitignore = crg_dir / ".gitignore"
    if not inner_gitignore.exists():
        inner_gitignore.write_text("# Auto-generated by code-rosetta — do not commit.\n*\n")

    return new_db


def _load_ignore_patterns(repo_root: Path) -> list[str]:
    patterns = list(DEFAULT_IGNORE_PATTERNS)
    for ignore_file_name in (".code-rosettaignore", ".code-review-graphignore"):
        ignore_file = repo_root / ignore_file_name
        if ignore_file.exists():
            for line in ignore_file.read_text().splitlines():
                line = line.strip()
                if line and not line.startswith("#"):
                    patterns.append(line)
    return patterns


def _should_ignore(path: str, patterns: list[str]) -> bool:
    return any(fnmatch.fnmatch(path, p) for p in patterns)


def _is_binary(path: Path) -> bool:
    try:
        chunk = path.read_bytes()[:8192]
        return b"\x00" in chunk
    except (OSError, PermissionError):
        return True


_GIT_TIMEOUT = int(os.environ.get("CRG_GIT_TIMEOUT", "30"))


def get_changed_files(repo_root: Path, base: str = "HEAD~1") -> list[str]:
    try:
        result = subprocess.run(
            ["git", "diff", "--name-only", base],
            capture_output=True, text=True,
            cwd=str(repo_root), timeout=_GIT_TIMEOUT,
        )
        if result.returncode != 0:
            result = subprocess.run(
                ["git", "diff", "--name-only", "--cached"],
                capture_output=True, text=True,
                cwd=str(repo_root), timeout=_GIT_TIMEOUT,
            )
        return [f.strip() for f in result.stdout.splitlines() if f.strip()]
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []


def get_staged_and_unstaged(repo_root: Path) -> list[str]:
    try:
        result = subprocess.run(
            ["git", "status", "--porcelain"],
            capture_output=True, text=True,
            cwd=str(repo_root), timeout=_GIT_TIMEOUT,
        )
        files = []
        for line in result.stdout.splitlines():
            if len(line) > 3:
                entry = line[3:].strip()
                if " -> " in entry:
                    entry = entry.split(" -> ", 1)[1]
                files.append(entry)
        return files
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []


def get_all_tracked_files(repo_root: Path) -> list[str]:
    try:
        result = subprocess.run(
            ["git", "ls-files"],
            capture_output=True, text=True,
            cwd=str(repo_root), timeout=_GIT_TIMEOUT,
        )
        return [f.strip() for f in result.stdout.splitlines() if f.strip()]
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []


def collect_all_files(repo_root: Path) -> list[str]:
    ignore_patterns = _load_ignore_patterns(repo_root)
    exts = supported_extensions()
    files = []

    tracked = get_all_tracked_files(repo_root)
    if tracked:
        candidates = tracked
    else:
        candidates = [
            str(p.relative_to(repo_root))
            for p in repo_root.rglob("*")
            if p.is_file()
        ]

    for rel_path in candidates:
        if _should_ignore(rel_path, ignore_patterns):
            continue
        full_path = repo_root / rel_path
        if not full_path.is_file() or full_path.is_symlink():
            continue
        if full_path.suffix.lower() not in exts:
            continue
        if _is_binary(full_path):
            continue
        files.append(rel_path)

    return files


def find_dependents(store: GraphStore, file_path: str) -> list[str]:
    dependents = set()
    edges = store.get_edges_by_target(file_path)
    for e in edges:
        if e.kind in ("IMPORTS", "IMPORTS_FROM"):
            dependents.add(e.file_path)

    nodes = store.get_nodes_by_file(file_path)
    for node in nodes:
        for e in store.get_edges_by_target(node.qualified_name):
            if e.kind in ("CALLS", "IMPORTS", "IMPORTS_FROM", "INHERITS",
                          "READS_CONFIG", "RENDERS", "REFERENCES"):
                dependents.add(e.file_path)

    dependents.discard(file_path)
    return list(dependents)


def full_build(repo_root: Path, store: GraphStore) -> dict:
    files = collect_all_files(repo_root)

    # Purge stale data — only for files under this repo root
    repo_root_str = str(repo_root)
    existing_files = set(store.get_all_files())
    current_abs = {str(repo_root / f) for f in files}
    for stale in existing_files - current_abs:
        if stale.startswith(repo_root_str):
            store.remove_file_data(stale)

    total_nodes = 0
    total_edges = 0
    errors = []
    all_nodes = []
    all_edges = []
    file_count = len(files)

    for i, rel_path in enumerate(files, 1):
        full_path = repo_root / rel_path
        try:
            source = full_path.read_bytes()
            fhash = hashlib.sha256(source).hexdigest()
            nodes, edges = parse_file(full_path, source)
            store.store_file_nodes_edges(str(full_path), nodes, edges, fhash)
            total_nodes += len(nodes)
            total_edges += len(edges)
            all_nodes.extend(nodes)
            all_edges.extend(edges)
        except (OSError, PermissionError) as e:
            errors.append({"file": rel_path, "error": str(e)})
        except Exception as e:
            logger.warning("Error parsing %s: %s", rel_path, e)
            errors.append({"file": rel_path, "error": str(e)})
        if i % 50 == 0 or i == file_count:
            logger.info("Progress: %d/%d files parsed", i, file_count)

    # Cross-language reference detection pass
    # Include nodes/edges already in the store (from other repos) for cross-repo detection
    try:
        existing_graph_nodes = []
        existing_graph_edges = []
        for gn in store._conn.execute("SELECT * FROM nodes").fetchall():
            existing_graph_nodes.append(NodeInfo(
                kind=gn["kind"], name=gn["name"], qualified_name=gn["qualified_name"],
                file_path=gn["file_path"], line_start=gn["line_start"] or 0,
                line_end=gn["line_end"] or 0, language=gn["language"] or "",
                parent_name=gn["parent_name"] or "", params=gn["params"] or "",
                return_type=gn["return_type"] or "", modifiers=gn["modifiers"] or "",
                is_test=bool(gn["is_test"]),
                extra=_json.loads(gn["extra"]) if gn["extra"] else {},
            ))
        for ge in store._conn.execute("SELECT * FROM edges").fetchall():
            existing_graph_edges.append(EdgeInfo(
                kind=ge["kind"], source_qualified=ge["source_qualified"],
                target_qualified=ge["target_qualified"], file_path=ge["file_path"],
                line=ge["line"],
                extra=_json.loads(ge["extra"]) if ge["extra"] else {},
            ))
        xref_edges = cross_reference_detector.detect(existing_graph_nodes, existing_graph_edges)
        for edge in xref_edges:
            store.upsert_edge(edge)
        total_edges += len(xref_edges)
        if xref_edges:
            logger.info("Cross-references: %d edges detected", len(xref_edges))
    except Exception as e:
        logger.warning("Cross-reference detection failed: %s", e)

    store.set_metadata("last_updated", time.strftime("%Y-%m-%dT%H:%M:%S"))
    store.set_metadata("last_build_type", "full")
    store.commit()

    return {
        "files_parsed": len(files),
        "total_nodes": total_nodes,
        "total_edges": total_edges,
        "cross_ref_edges": len(xref_edges) if 'xref_edges' in dir() else 0,
        "errors": errors,
    }


def incremental_update(
    repo_root: Path,
    store: GraphStore,
    base: str = "HEAD~1",
    changed_files: list[str] | None = None,
) -> dict:
    ignore_patterns = _load_ignore_patterns(repo_root)

    if changed_files is None:
        changed_files = get_changed_files(repo_root, base)

    if not changed_files:
        return {
            "files_updated": 0,
            "total_nodes": 0,
            "total_edges": 0,
            "changed_files": [],
            "dependent_files": [],
        }

    dependent_files: set[str] = set()
    for rel_path in changed_files:
        full_path = str(repo_root / rel_path)
        deps = find_dependents(store, full_path)
        for d in deps:
            try:
                dependent_files.add(str(Path(d).relative_to(repo_root)))
            except ValueError:
                dependent_files.add(d)

    all_files = set(changed_files) | dependent_files
    total_nodes = 0
    total_edges = 0
    errors = []

    for rel_path in all_files:
        if _should_ignore(rel_path, ignore_patterns):
            continue
        abs_path = repo_root / rel_path
        if not abs_path.is_file():
            store.remove_file_data(str(abs_path))
            continue
        if get_parser(abs_path) is None:
            continue

        try:
            source = abs_path.read_bytes()
            fhash = hashlib.sha256(source).hexdigest()
            existing_nodes = store.get_nodes_by_file(str(abs_path))
            if existing_nodes and existing_nodes[0].file_hash == fhash:
                continue

            nodes, edges = parse_file(abs_path, source)
            store.store_file_nodes_edges(str(abs_path), nodes, edges, fhash)
            total_nodes += len(nodes)
            total_edges += len(edges)
        except (OSError, PermissionError) as e:
            errors.append({"file": rel_path, "error": str(e)})
        except Exception as e:
            logger.warning("Error parsing %s: %s", rel_path, e)
            errors.append({"file": rel_path, "error": str(e)})

    store.set_metadata("last_updated", time.strftime("%Y-%m-%dT%H:%M:%S"))
    store.set_metadata("last_build_type", "incremental")
    store.commit()

    return {
        "files_updated": len(all_files),
        "total_nodes": total_nodes,
        "total_edges": total_edges,
        "changed_files": list(changed_files),
        "dependent_files": list(dependent_files),
        "errors": errors,
    }
